# Generated by Django 4.2.17 on 2025-01-07 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('buying_currency', models.CharField(max_length=3)),
                ('selling_currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
